### PR TITLE
Adds responsive design + improved consistency

### PR DESCRIPTION
**Pull request by henrybhudson**
Review requested from Alessandro as I made the communications page match the design of other pages.

### CODE REVIEW

**Comment by vzze** [comment]
I'll merge tomorrow if Alex doesn't respond

**Review by acassani055 — COMMENTED** [review]
Sorry I didn't see this before. I've already made the communication page match the other pages on my own branch and also included some more information on the page. Would it be better to merge this and then merge my changes later?

**Comment by henrybhudson** [comment]
Yeah that works. I may have to go in tomorrow and change a few styling things but that's no problem

**Comment by acassani055** [comment]
I'll just leave the merging and resolving conflicts to Edi then.

**Comment by vzze** [comment]
> I'll just leave the merging and resolving conflicts to Edi then.

Don't worry merge order doesn't matter, feel free to continue working and when finished just PR, if there are multiple PRs I'll just deal with conflicts

**Review by vzze — CHANGES_REQUESTED** [review]
## broken dropdowns

It seems the dropdown menu doesn't work on the communication, medical and transportation pages.

The reason is because the properties are not named correctly, i.e. in `index.html` `data-bs-toggle` and `data-bs-target` are named correctly, while in the rest of the files they're misspelled.

### communication.html

Line 17

```html
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
```

* `data-toggle` property should become `data-bs-toggle`
* `data-target` property should become `data-bs-target`

### medical.html

Ditto line 23

### transportation.html

Ditto line 20

## minor visual glitches

* medical, communication and transportation have a minor visual glitch when resizing (at least on Firefox)

**Comment by henrybhudson** [comment]
Will look at this later today, thanks

**Comment by henrybhudson** [comment]
This is ready to merge

**Comment by vzze** [comment]
what about the dropdowns?

**Comment by henrybhudson** [comment]
Dropdowns were already done and work on my side - the CSS bug has been fixed in my local but not sure how to add that to this pull request so will just create another request later

**Comment by vzze** [comment]
dw, I'll fix em rn

**Comment by vzze** [comment]
you might have to git pull in case you don't delete your branch

**Pull request merged**
